### ISSUE TITLE
please contact me

### ISSUE THREAD

**Issue by gotwicked** [teejayx6/api#1]
please add me on discord so we can talk abt some old stuff
> **discord**
- [famous#6603](https://discord.com/users/famous#6603)

**Comment by coder5010** [comment]
ummmmmmm okokok this still your tag? my name is x im finna add you

**Comment by rxnk** [comment]
i change my tag a bunch and have had friends disabled sry, join https://discord.gg/pycord and DM me .()#1030

**Comment by coder5010** [comment]
ur dms off

**Comment by coder5010** [comment]
> join

឵឵x#0639
add me 
឵឵x#0639


copy that bc it has a special char
